# Generated by Django 4.1.2 on 2022-11-22 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0005_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group', to='auth.group', verbose_name='Группа доступа'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='employees.jobtitles', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
