# Generated by Django 4.1.2 on 2022-11-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0006_employee_group_alter_employee_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='group', to='auth.group', verbose_name='Группа доступа'),
        ),
    ]
