# Generated by Django 4.1.2 on 2022-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Архив'),
        ),
    ]
