# Generated by Django 4.1.2 on 2022-11-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
