# Generated by Django 4.1.2 on 2022-11-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_devision_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default="2022-11-14"),
            preserve_default=False,
        ),
    ]
