# Generated by Django 4.1.2 on 2022-11-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='devision_id',
            new_name='devision',
        ),
    ]
