# Generated by Django 4.1.2 on 2022-11-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_group'),
        ('orders', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='equipment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='devision',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.devision', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='Дата наряда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='worker',
            field=models.ManyToManyField(related_name='orders', to='employees.employee', verbose_name='Рабочие'),
        ),
    ]
