# Generated by Django 4.1.2 on 2022-11-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_equipment_alter_order_devision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('tree_id', 'level')},
        ),
        migrations.AddField(
            model_name='equipment',
            name='techcode',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
